blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/divyamohan1993/dmj-one-pdf-authenticator/discussions
    about: Ask questions and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/divyamohan1993/dmj-one-pdf-authenticator/blob/main/README.md
    about: Read the project documentation
  - name: 🔒 Security Issue
    url: https://github.com/divyamohan1993/dmj-one-pdf-authenticator/security/advisories/new
    about: Report a security vulnerability privately
  - name: 💼 Commercial Support
    url: mailto:contact@dmj.one
    about: Get commercial support and consulting services
