name = "dmj-one-signer"
main = "src/index.ts"
compatibility_date = "2025-10-01"

# Routes for the signer, admin and verifier endpoints.
routes = [
  { pattern = "api.dmj.one/*", zone_name = "dmj.one" },
  { pattern = "sign.dmj.one/*", zone_name = "dmj.one" },
  { pattern = "verify.dmj.one/*", zone_name = "dmj.one" }
]

[[d1_databases]]
# Bind the D1 database used to store sessions, documents, signatures, etc.
binding = "DB"
database_name = "dmj_d1"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[build]
# No build step is needed because we compile TypeScript directly in the Worker runtime.
command = ""

[vars]
# Publicly visible variables. Secrets (e.g. ADMIN_PASS_HASH) are injected with `wrangler secret put`.
ISSUER = "dmj.one"
SESSION_COOKIE_NAME = "dmj_sess"
# Allowed origins for admin POSTs to prevent CSRF via cross‑domain forms.
ADMIN_ALLOWED_ORIGINS = "https://sign.dmj.one,https://api.dmj.one"

[triggers]
# Daily cron for cleanup of expired sessions and old nonces.
crons = ["0 3 * * *"]
