name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Close Stale Issues and PRs
    runs-on: ubuntu-latest
    
    steps:
      - name: Stale Action
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Stale issues
          days-before-issue-stale: 60
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: >
            This issue was automatically closed due to inactivity. Please feel free to
            reopen if you believe this is still relevant.
          exempt-issue-labels: 'pinned,security,bug,enhancement'
          
          # Stale PRs
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-pr-message: >
            This pull request was automatically closed due to inactivity. Please feel free to
            reopen if you would like to continue working on this.
          exempt-pr-labels: 'pinned,security,work-in-progress'
          
          # Operation settings
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true
